### ISSUE TITLE
[Bug] Program attempts to write to protected memory

### ISSUE THREAD

**Issue by LucasErG** [ermig1979/AntiDupl#72]
When attempting to compare over 100k pictures I have been getting this errror:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Object structure, Boolean allowValueClasses)
   at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr ptr, Type structureType)
   at AntiDupl.NET.CoreLib.StatusGet(ThreadType threadType, Int32 threadId)
   at AntiDupl.NET.SearchExecuterForm.EstimateSearchProgress()
   at AntiDupl.NET.SearchExecuterForm.TimerCallback(Object obj, EventArgs eventArgs)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9148 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
AntiDupl.NET
    Assembly Version: 2.3.10.0
    Win32 Version: 2.3.10
    CodeBase: file:///C:/Users/kulgi/Downloads/AntiDupl.NET-2.3.10d/AntiDupl.NET-2.3.10/AntiDupl.NET.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9136 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9147 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9136 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9136 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9136 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
prcmftg7
    Assembly Version: 2.3.10.0
    Win32 Version: 2.0.50727.9147 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
s9a6xu9l
    Assembly Version: 2.3.10.0
    Win32 Version: 2.0.50727.9147 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
gngwky6u
    Assembly Version: 2.3.10.0
    Win32 Version: 2.0.50727.9147 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by KoalaBear84** [comment]
This is now possibly fixed in #70 

Please retry with this version.

**Comment by KoalaBear84** [comment]
@LucasErG What are the testresults? Is it fixed?

**Comment by LucasErG** [comment]
I just scanned the folder that was consistently giving the error with version 2.3.10d and the bug didn't happen. I'm thinking there may have been a corrupted picture that may have been triggering the issue. I will continue to test other folders that gave me problems though.

**Comment by LucasErG** [comment]
for my amusement, I attempted to scan my entire pic hoard, 1,200,000+ pics. loading pictures was successful, but the comparing portion was not. The program closed itself with no error message or log at least that I know of anyway.

**Comment by mazzaferri** [comment]
I can reproduce this or a very similar crash on my machine with a sufficiently large image collection pretty much every single time. It's due to CoreLib.cs failing to correctly use Marshal.UnsafeAddrOfPinnedArrayElement(). The docs for that method indicate that it **MUST NOT BE CALLED** on an array **unless that array has been pinned or fixed**. The current method does not pin or fix the array.

There is a commit https://github.com/ermig1979/AntiDupl/commit/e27f25841e86567d8b125121859164c96e11830b that claims to fix the issue by wrapping those unsafe calls in a try {} catch {} block. That doesn't fix the issue - it merely mutates it into a different one (the program silently exits, or something else doesn't work right).

If I get my act together I'll try to put up a git pull request to actually fix the issue, but I don't use git much so it may take me a while. In the meantime, if someone wants to take code from here instead, here's the modified version of StatusGet() I wrote that fixes the issue:

`public CoreStatus StatusGet(CoreDll.ThreadType threadType, int threadId)
        {
            object statusObject = new CoreDll.adStatusW();
            byte[] status = new byte[Marshal.SizeOf(statusObject)];
            // MUST NOT CALL UnsafeAddrOfPinnedArrayElement() on an unpinned/unfixed array!
            unsafe
            {
                fixed (byte* buff = status)
                {
                    IntPtr pStatus = new IntPtr(buff);
                    if (m_dll.adStatusGetW(m_handle, threadType, new IntPtr(threadId), pStatus) == CoreDll.Error.Ok)
                    {
                        CoreDll.adStatusW statusW = (CoreDll.adStatusW)Marshal.PtrToStructure(pStatus, statusObject.GetType());
                        try
                        {
                            return new CoreStatus(ref statusW);
                        }
                        catch (Exception)
                        {
                            return null;
                        }
                    }
                }
            }
            return null;
        }`

**Comment by mazzaferri** [comment]
Also note that there are other calls in `CoreLib.cs` to `Marshal.UnsafeAddrOfPinnedArrayElement()` on arrays that have not been pinned or fixed. They don't seem to cause crashes anywhere near as often as the one in `StatusGet()` does, but they are nevertheless bugs that should be fixed.

**Comment by ermig1979** [comment]
I dealt with C# very time ago. Could you check my solution of this bug:

        public CoreStatus StatusGet(CoreDll.ThreadType threadType, int threadId)
        {
            try
            {
                object statusObject = new CoreDll.adStatusW();
                byte[] statusArray = new byte[Marshal.SizeOf(statusObject)];
                GCHandle statusHandle = GCHandle.Alloc(statusArray, GCHandleType.Pinned);
                if (m_dll.adStatusGetW(m_handle, threadType, new IntPtr(threadId), statusHandle.AddrOfPinnedObject()) == CoreDll.Error.Ok)
                {
                    CoreDll.adStatusW statusW = (CoreDll.adStatusW)Marshal.PtrToStructure(statusHandle.AddrOfPinnedObject(), statusObject.GetType());
                    return new CoreStatus(ref statusW);
                }
                statusHandle.Free();
            }
            catch(Exception)
            {
            }
            return null;
        }

Are there any troubles?

**Comment by mazzaferri** [comment]
Hi ermig1979, I don't do much native interop so it takes me a while too. That solution has a couple of known issues:

- It will leak a pinned `GCHandle` each time an Exception is thrown, which will make future memory allocations more fragmented. That normally won't matter much as we don't expect many exceptions.

- It doesn't free the `GCHandle` if the DLL call succeeds, so it consumes large amounts of memory (and usually fragments the heap making the problem much worse). It hit 12GB of active private working set half way through a scenario that normally uses just over 1GB by the end.

Both issues can be fixed via a `try {...} finally {...}` block:

```C#
public CoreStatus StatusGet(CoreDll.ThreadType threadType, int threadId)
{
    try
    {
        object statusObject = new CoreDll.adStatusW();
        byte[] statusArray = new byte[Marshal.SizeOf(statusObject)];
        GCHandle statusHandle = GCHandle.Alloc(statusArray, GCHandleType.Pinned);
        try
        {
            if (m_dll.adStatusGetW(m_handle, threadType, new IntPtr(threadId), statusHandle.AddrOfPinnedObject()) == CoreDll.Error.Ok)
            {
                CoreDll.adStatusW statusW = (CoreDll.adStatusW)Marshal.PtrToStructure(statusHandle.AddrOfPinnedObject(), statusObject.GetType());
                return new CoreStatus(ref statusW);
            }
        }
        finally
        {
            statusHandle.Free();
        }
    }
    catch (Exception ex)
    {
        // Debug.WriteLine(ex.Message);
    }
    return null;
}
```
And when I test that memory usage is about typical, and it hasn't crashed yet. The old code would normally have crashed three or four times in the same amount of testing.

So that looks like it works. However it might be easier to use the newer language features since about C# 7.3 rather than messing around with allocating and freeing a `GCHandle`. The `fixed(byte * buff = status) {}` statement in my code snippet pins `status` in memory for the duration of that block and allows safe access via the `buff` pointer (see [docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/fixed-statement)). However it must appear inside an `unsafe` context, so it's no good if you have a strict requirement to avoid `unsafe`.

You could also use `stackalloc` to allocate a local variable on the stack where its location is fixed for the duration of the method and hence doesn't need to be explicitly pinned (see [docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/stackalloc)), but I think that may also require `unsafe`.

And the `Span<T>' classes are also useful abstractions (but probably not here seeing the interop has already been written).

So [this comment](https://github.com/dotnet/runtime/issues/27091#issuecomment-411475536) from a .NET Platform team member with a recommendation is worth reading as a general principle, even though it was about a scenario using spans:

> The preferred pattern is to use unmanaged pointer in the PInvoke signature and use fixed block to call it ... This pattern best describes the intent and avoids corner case bugs that the other patterns suffer from.

**Comment by mazzaferri** [comment]
While we're on the topic, all other calls to `Marshal.UnsafeAddrOfPinnedArrayElement()` are almost certainly bugs because they are called on variables that are not pinned, so the variable may be moved by the GC before the DLL method tries to write to it. 

I haven't seen any of those produce a crash yet, but I see bogus comparison results in the UI (e.g. pairs of image files that are identical byte-for-byte are reported to have significant differences) that might result from such a bug.

Some of those calls can probably be simplified if you dig into the PInvoke and marshalling rules and tweak the PInvoke declarations (e.g. in some circumstances blittable variables passed by reference are pinned by the PInvoke marshaller without you having to explicitly do it), but it's probably simpler to pick an implementation pattern and use it everywhere.
